stages:
  - "test"

.test-template:
  stage: test
  image: python:3.9.16-slim-buster
  tags:
    - kubernetes-runner
    - docker-runner
  except:
    - tags
  before_script:
    - pip install poetry
    - poetry config virtualenvs.create false
    - poetry install

black:
  extends:
    - .test-template
  script:
    - black --check .

flake8:
  extends:
    - .test-template
  script:
    - flake8 --count .

mypy:
  extends:
    - .test-template
  script:
    - mypy .
