name: Publish Tag

on:
  push:
    branches:
      - master

jobs:
  publish_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install Poetry
        run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -
      - name: Get version
        id: get_version
        run: echo ::set-output name=version::$(poetry version --no-interaction)
      - name: Create and push tag
        uses: mathieudutour/github-tag-action@v5.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ steps.get_version.outputs.version }}
          message: "Release version v${{ steps.get_version.outputs.version }}"
